#!/bin/sh
#
# deathstar         Boot 
#
# chkconfig: 2345 90 60
# description: Death Star appliance boot strap \

### BEGIN INIT INFO
# Provides: deathstar
# Required-Start: $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start:  2345
# Default-Stop: 90
# Short-Description: sets up a few things and starts the web app and IDE
# Description: deathstar appliance boot strap
### END INIT INFO

generateUniqueSSHKey () {
    # If the appliance doesn't have a key pair, generate one
    SSHKEY=/root/.ssh/id_rsa
    if [ ! -f $SSHKEY ]; then
            ssh-keygen -t rsa -N "" -f $SSHKEY -q
    fi
}

doOnceTasks () {
    # Do Once Tasks - happens only once, on the first boot, or if specifically
    # invoked by the user.
    # We don't want these happening every time, because that would lead
    # to unpredictable behaviour for users as changes are (un)done by this script

    doVBoxOnMacNetworkSetup
    doGitPull
 
}

doVBoxOnMacNetworkSetup () {

   # Check if I'm running on Mac OS X under VirtualBox
    # We look for the DHCP-assigned address for a VirtualBox Host-only network
    
    VBox=`ifconfig eth0 | grep "192.168.56" | wc -l`
    
    # If we are under VirtualBox, we'll switch to static IP addressing on
    # the host-only network, but under the DHCP range
    
    if [ $VBox = 1 ]; then
        echo "DEVICE=eth0
BOOTPROTO=static
IPADDR=192.168.56.25
NETMASK=255.255.255.0
ONBOOT=on" > /etc/sysconfig/network-scripts/ifcfg-eth0

        # and restart the network with the new address...    
        service network restart
    fi
}

doGitPull () {
    # Update the installed web app to the latest version before launching
    cd /opt/deathstar-appliance
    git pull
}

doFirstBootUpdate () {
    # Here we pull the latest update for this machine
    # This means that we don't have to keep uploading new images
    # we can use the same image, and push the delta updates out via this mechanism
}

start () {
    generateUniqueSSHKey

    # Tasks that should only be done once

    DO_ONCE=0

    if [ -f /opt/deathstar-appliance/.doOnce -o $1 = "firstboot" ]; then
        DO_ONCE=1
        doOnceTasks
        rm /opt/deathstar-appliance/.doOnce
    fi

    # Start the Death Star web application
    service deathstar-webapp start

    # The first boot update relies on the web app, so we needed to
    # wait for it to start before proceeding
    if [ $DO_ONCE = 1 ]; then
        doFirstBootUpdate
    fi

    # Now start the IDE
    service deathstar-ide start
}

status () {
    service deathstar-webapp status
    service deathstar-ide status
}

stop () {
    service deathstar-webapp stop
    service deathstar-ide stop
}

restart () {
    service deathstar-webapp restart
    service deathstar-ide restart
}

case "$1" in
    start)
        $1 
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    status)
    	$1
    	;;
    firstboot)
        start $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status|firstboot}"
        exit 2
esac
exit $?