#!/bin/sh
#
# deathstar-firstboot         First boot activities
#
# chkconfig: 2345 90 60
# description: deathstar appliance first boot tasks \

### BEGIN INIT INFO
# Provides: deathstar-firstboot
# Required-Start: $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start:  2345
# Default-Stop: 90
# Short-Description: sets up a few things
# Description: deathstar appliance first boot tasks
### END INIT INFO

# Create an ssh key pair for this appliance

SSHKEY=/root/.ssh/id_rsa

if [ -f $SSHKEY ]; then
	chkconfig deathstar-firstboot off	
	exit
fi

ssh-keygen -t rsa -N "" -f $SSHKEY -q

