#!/bin/sh
#
# deathstar         Boot 
#
# chkconfig: 2345 90 60
# description: Death Star appliance boot strap \

### BEGIN INIT INFO
# Provides: deathstar
# Required-Start: $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start:  2345
# Default-Stop: 90
# Short-Description: sets up a few things and starts the web app and IDE
# Description: deathstar appliance boot strap
### END INIT INFO

FIRST_BOOT_UPDATE_URL=http://127.0.0.1/initialize?from=http://raw.github.com/jwulf/deathstar-appliance-updates/master/00/firstboot.json


generateUniqueSSHKey () {
    # If the appliance doesn't have a key pair, generate one
    SSHKEY=/root/.ssh/id_rsa
    if [ ! -f $SSHKEY ]; then
            ssh-keygen -t rsa -N "" -f $SSHKEY -q
    fi
}

doOnceTasks () {
    # Do Once Tasks - happens only once, on the first boot, or if specifically
    # invoked by the user.
    # We don't want these happening every time, because that would lead
    # to unpredictable behaviour for users as changes are (un)done by this script

    doVBoxOnMacNetworkSetup
    doGitPull
 
}

doVBoxOnMacNetworkSetup () {

    # Under VirtualBox we need two adapters - a host-only one with a static
    # IP for communication with the host, and a NAT one with a dynamic IP
    # to communicate with the world (update servers, PressGang, etc)

    VIRTUALBOX_DHCP=192.168.56
    VIRTUALBOX_DHCP_IP_DETECTED=1

    # Check if I'm running on Mac OS X under VirtualBox
    # We look for the DHCP-assigned address for a VirtualBox Host-only network
    
    IP_ADDRESS=`ifconfig eth0 | grep "$VIRTUALBOX_DHCP" | wc -l`
    
    # If we are under VirtualBox, we'll switch to static IP addressing on
    # the host-only network, with a static IP under the DHCP range
    
    if [ $IP_ADDRESS = $VIRTUALBOX_DHCP_IP_DETECTED ]; then
        echo "DEVICE=eth0
BOOTPROTO=static
IPADDR=192.168.56.25
NETMASK=255.255.255.0
HWADDR=00:02:B3:F7:FE:2A
ONBOOT=on" > /etc/sysconfig/network-scripts/ifcfg-eth0

    # and create a second adapter for the NAT network

        echo "DEVICE=eth1
BOOTPROTO=dhcp
HWADDR=00:02:B3:F7:FE:2A
ONBOOT=on" > /etc/sysconfig/network-scripts/ifcfg-eth1

        # and restart the network with the new adapters...    
        service network restart
    fi
}

doGitPull () {
    # Update the installed web app to the latest version before launching
    cd /opt/deathstar-appliance
    git pull
}

doFirstBootUpdate () {
    # Here we pull the latest update for this machine
    # This means that we don't have to keep uploading new images
    # we can use the same image, and push the delta updates out via this mechanism

    curl -L $FIRST_BOOT_UPDATE_URL
}

start () {
    generateUniqueSSHKey

    # Tasks that should only be done once

    DO_ONCE=0

    if [ -f /opt/deathstar-appliance/.doOnce ] || [ "$1" = "firstboot" ]; then
        DO_ONCE=1
        doOnceTasks
        rm /opt/deathstar-appliance/.doOnce
    fi

    # Start the Death Star web application
    service deathstar-webapp start

    # The first boot update relies on the web app, so we needed to
    # wait for it to start before proceeding
    if [ $DO_ONCE = 1 ]; then
        doFirstBootUpdate
    fi

    # Now start the IDE
    service deathstar-ide start
}

status () {
    service deathstar-webapp status
    service deathstar-ide status
}

stop () {
    service deathstar-webapp stop
    service deathstar-ide stop
}

restart () {
    service deathstar-webapp restart
    service deathstar-ide restart
}

case "$1" in
    start)
        $1 
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    status)
    	$1
    	;;
    firstboot)
        start $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status|firstboot}"
        exit 2
esac
exit $?