#!/bin/sh
#
# motd	Prepares /etc/motd file
#
# chkconfig: 2345 99 05
# description: Prepares /etc/motd file
#
### BEGIN INIT INFO
# Provides: motd
# Required-Start: network
# Default-Start: 2345
# Default-Stop: 0 1 6
# Short-Description: Prepares /etc/motd file
# Description: Prepares /etc/motd file
### END INIT INFO

LOGO=/opt/logo
DEETS=/opt/contact_details
HOSTNAME=`/bin/uname -a | awk '{print $2}'`
IP_ADDRESS=`ip addr list eth0 | grep "inet " | cut -d' ' -f6 | cut -d/ -f1 | head -1`

cat $LOGO > /etc/motd
VERSION=`cat /root/VERSION`
echo -e "\nAppliance:\tDeath Star Appliance $VERSION\nHostname:\t$HOSTNAME\nIP Address:\t$IP_ADDRESS\n" >> /etc/motd
echo -e "\nblog:\thttp://tinyurl.com/deathstar-blog\nirc:\t#deathstar on Freenode\nbug:\thttp://tinyurl.com/new-bug-deathstar\nbugs:\thttp://tinyurl.com/deathstar-bugs\n" >> /etc/motd

exit 0

